// <auto-generated />
using GithubIssueTriager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GithubIssueTriager.Api.Migrations
{
    [DbContext(typeof(TriageDbContext))]
    partial class TriageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GithubIssueTriager.Api.Data.AppSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("GitHubIssueNumber")
                        .HasColumnType("integer");

                    b.Property<string>("GitHubOwner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubRepo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssueSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocalJsonPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("LowConfidenceReviewThreshold")
                        .HasColumnType("double precision");

                    b.Property<int>("PriorityCritical")
                        .HasColumnType("integer");

                    b.Property<int>("PriorityHigh")
                        .HasColumnType("integer");

                    b.Property<int>("PriorityMedium")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("GithubIssueTriager.Api.Data.TriageHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NextStep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriorityScore")
                        .HasColumnType("integer");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriagedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("triage_history", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
